### ISSUE TITLE
All links are broken

### ISSUE THREAD

**Issue by mimaison** [ibm-learning-skills-dev/ibm-learning-skills-dev.github.io#26]
If you visit the github.io page, https://ibm-learning-skills-dev.github.io/, all links are broken.

It seems all links contain this extra path `ibm-learning-skills-dev.github.io`. 

For example, `https://ibm-learning-skills-dev.github.io/ibm-learning-skills-dev.github.io/education/courseinfo.html` should be `https://ibm-learning-skills-dev.github.io/education/courseinfo.html`.

**Comment by krtilley** [comment]
Fixed
